package civ5

object Constants {
  final val TECH_TO_COST_MAP = Map(
    "TECH_AGRICULTURE" -> 20,
    "TECH_POTTERY" -> 60,
    "TECH_ANIMAL_HUSBANDRY" -> 60,
    "TECH_ARCHERY" -> 100,
    "TECH_MINING" -> 60,
    "TECH_SAILING" -> 100,
    "TECH_CALENDAR" -> 100,
    "TECH_WRITING" -> 130,
    "TECH_TRAPPING" -> 60,
    "TECH_THE_WHEEL" -> 60,
    "TECH_MASONRY" -> 100,
    "TECH_BRONZE_WORKING" -> 100,
    "TECH_OPTICS" -> 130,
    "TECH_HORSEBACK_RIDING" -> 100,
    "TECH_MATHEMATICS" -> 130,
    "TECH_CONSTRUCTION" -> 130,
    "TECH_PHILOSOPHY" -> 275,
    "TECH_DRAMA" -> 275,
    "TECH_CURRENCY" -> 275,
    "TECH_ENGINEERING" -> 275,
    "TECH_IRON_WORKING" -> 130,
    "TECH_THEOLOGY" -> 500,
    "TECH_CIVIL_SERVICE" -> 700,
    "TECH_GUILDS" -> 700,
    "TECH_METAL_CASTING" -> 275,
    "TECH_COMPASS" -> 700,
    "TECH_EDUCATION" -> 500,
    "TECH_CHIVALRY" -> 500,
    "TECH_MACHINERY" -> 700,
    "TECH_PHYSICS" -> 500,
    "TECH_STEEL" -> 500,
    "TECH_ASTRONOMY" -> 1750,
    "TECH_ACOUSTICS" -> 2400,
    "TECH_BANKING" -> 1750,
    "TECH_PRINTING_PRESS" -> 1750,
    "TECH_GUNPOWDER" -> 1750,
    "TECH_NAVIGATION" -> 2400,
    "TECH_ARCHITECTURE" -> 2400,
    "TECH_ECONOMICS" -> 2400,
    "TECH_METALLURGY" -> 2400,
    "TECH_CHEMISTRY" -> 1750,
    "TECH_ARCHAEOLOGY" -> 5150,
    "TECH_SCIENTIFIC_THEORY" -> 3600,
    "TECH_INDUSTRIALIZATION" -> 5150,
    "TECH_RIFLING" -> 3600,
    "TECH_MILITARY_SCIENCE" -> 5150,
    "TECH_FERTILIZER" -> 5150,
    "TECH_BIOLOGY" -> 8100,
    "TECH_ELECTRICITY" -> 8100,
    "TECH_STEAM_POWER" -> 3600,
    "TECH_DYNAMITE" -> 5150,
    "TECH_REFRIGERATION" -> 13000,
    "TECH_RADIO" -> 11000,
    "TECH_REPLACEABLE_PARTS" -> 8100,
    "TECH_FLIGHT" -> 11000,
    "TECH_RAILROAD" -> 3600,
    "TECH_PLASTIC" -> 11000,
    "TECH_ELECTRONICS" -> 16000,
    "TECH_BALLISTICS" -> 11000,
    "TECH_COMBUSTION" -> 8100,
    "TECH_PENICILIN" -> 13000,
    "TECH_ATOMIC_THEORY" -> 13000,
    "TECH_RADAR" -> 16000,
    "TECH_COMBINED_ARMS" -> 13000,
    "TECH_ECOLOGY" -> 19100,
    "TECH_NUCLEAR_FISSION" -> 16000,
    "TECH_ROCKETRY" -> 13000,
    "TECH_COMPUTERS" -> 16000,
    "TECH_TELECOM" -> 19100,
    "TECH_MOBILE_TACTICS" -> 19100,
    "TECH_ADVANCED_BALLISTICS" -> 19100,
    "TECH_SATELLITES" -> 19100,
    "TECH_ROBOTICS" -> 23400,
    "TECH_LASERS" -> 23400,
    "TECH_INTERNET" -> 23400,
    "TECH_GLOBALIZATION" -> 24450,
    "TECH_PARTICLE_PHYSICS" -> 24450,
    "TECH_NUCLEAR_FUSION" -> 24450,
    "TECH_NANOTECHNOLOGY" -> 24450,
    "TECH_STEALTH" -> 23400,
    "TECH_FUTURE_TECH" -> 28550,
    "TECH_CORPORATIONS" -> 8100
  )

  final val GRIDX_TO_ERA_MAP = Map(
    1 -> 1, // Ancient
    2 -> 1, // Ancient
    3 -> 2, // Classical
    4 -> 2, // Classical
    5 -> 3, // Medieval
    6 -> 3, // Medieval
    7 -> 4, // Renaissance
    8 -> 4, // Renaissance
    9 -> 5, // Industrial
    10 -> 5, // Industrial
    11 -> 6, // Modern
    12 -> 6, // Modern
    13 -> 7, // Atomic
    14 -> 7, // Atomic
    15 -> 8, // Information
    16 -> 8, // Information
    17 -> 9, // Information
    18 -> 10 // Future
  )

  final val TECH_TO_GRIDX_MAP = Map(
    "TECH_AGRICULTURE" -> 0,
    "TECH_POTTERY" -> 1,
    "TECH_ANIMAL_HUSBANDRY" -> 1,
    "TECH_ARCHERY" -> 2,
    "TECH_MINING" -> 1,
    "TECH_SAILING" -> 2,
    "TECH_CALENDAR" -> 2,
    "TECH_WRITING" -> 3,
    "TECH_TRAPPING" -> 1,
    "TECH_THE_WHEEL" -> 1,
    "TECH_MASONRY" -> 2,
    "TECH_BRONZE_WORKING" -> 2,
    "TECH_OPTICS" -> 3,
    "TECH_HORSEBACK_RIDING" -> 2,
    "TECH_MATHEMATICS" -> 3,
    "TECH_CONSTRUCTION" -> 3,
    "TECH_PHILOSOPHY" -> 4,
    "TECH_DRAMA" -> 4,
    "TECH_CURRENCY" -> 4,
    "TECH_ENGINEERING" -> 4,
    "TECH_IRON_WORKING" -> 3,
    "TECH_THEOLOGY" -> 5,
    "TECH_CIVIL_SERVICE" -> 6,
    "TECH_GUILDS" -> 6,
    "TECH_METAL_CASTING" -> 4,
    "TECH_COMPASS" -> 6,
    "TECH_EDUCATION" -> 5,
    "TECH_CHIVALRY" -> 5,
    "TECH_MACHINERY" -> 6,
    "TECH_PHYSICS" -> 5,
    "TECH_STEEL" -> 5,
    "TECH_ASTRONOMY" -> 7,
    "TECH_ACOUSTICS" -> 8,
    "TECH_BANKING" -> 7,
    "TECH_PRINTING_PRESS" -> 7,
    "TECH_GUNPOWDER" -> 7,
    "TECH_NAVIGATION" -> 8,
    "TECH_ARCHITECTURE" -> 8,
    "TECH_ECONOMICS" -> 8,
    "TECH_METALLURGY" -> 8,
    "TECH_CHEMISTRY" -> 7,
    "TECH_ARCHAEOLOGY" -> 10,
    "TECH_SCIENTIFIC_THEORY" -> 9,
    "TECH_INDUSTRIALIZATION" -> 10,
    "TECH_RIFLING" -> 9,
    "TECH_MILITARY_SCIENCE" -> 10,
    "TECH_FERTILIZER" -> 10,
    "TECH_BIOLOGY" -> 11,
    "TECH_ELECTRICITY" -> 11,
    "TECH_STEAM_POWER" -> 9,
    "TECH_DYNAMITE" -> 10,
    "TECH_REFRIGERATION" -> 13,
    "TECH_RADIO" -> 12,
    "TECH_REPLACEABLE_PARTS" -> 11,
    "TECH_FLIGHT" -> 12,
    "TECH_RAILROAD" -> 9,
    "TECH_PLASTIC" -> 12,
    "TECH_ELECTRONICS" -> 14,
    "TECH_BALLISTICS" -> 12,
    "TECH_COMBUSTION" -> 11,
    "TECH_PENICILIN" -> 13,
    "TECH_ATOMIC_THEORY" -> 13,
    "TECH_RADAR" -> 14,
    "TECH_COMBINED_ARMS" -> 13,
    "TECH_ECOLOGY" -> 15,
    "TECH_NUCLEAR_FISSION" -> 14,
    "TECH_ROCKETRY" -> 13,
    "TECH_COMPUTERS" -> 14,
    "TECH_TELECOM" -> 15,
    "TECH_MOBILE_TACTICS" -> 15,
    "TECH_ADVANCED_BALLISTICS" -> 15,
    "TECH_SATELLITES" -> 15,
    "TECH_ROBOTICS" -> 16,
    "TECH_LASERS" -> 16,
    "TECH_INTERNET" -> 16,
    "TECH_GLOBALIZATION" -> 17,
    "TECH_PARTICLE_PHYSICS" -> 17,
    "TECH_NUCLEAR_FUSION" -> 17,
    "TECH_NANOTECHNOLOGY" -> 17,
    "TECH_STEALTH" -> 16,
    "TECH_FUTURE_TECH" -> 18,
    "TECH_CORPORATIONS" -> 11
  )

  // final val TECHS_AT_GRIDX_MAP = TECH_TO_GRIDX_MAP.values.groupBy(identity).mapValues(_.size).map(identity)
  final val TECHS_AT_GRIDX_MAP =  Map(0 -> 1, 5 -> 5, 10 -> 5, 14 -> 4, 1 -> 5, 6 -> 4, 9 -> 4, 13 -> 5, 2 -> 6, 17 -> 4, 12 -> 4, 7 -> 5, 3 -> 5, 18 -> 1, 16 -> 4, 11 -> 5, 8 -> 5, 4 -> 5, 15 -> 5)

  final val CIV_TAG_TO_TEXT_MAP = Map(
    "CIVILIZATION_AMERICA" -> "America",
    "CIVILIZATION_ARABIA" -> "Arabia",
    "CIVILIZATION_AZTEC" -> "The Aztecs",
    "CIVILIZATION_CHINA" -> "China",
    "CIVILIZATION_EGYPT" -> "Egypt",
    "CIVILIZATION_ENGLAND" -> "England",
    "CIVILIZATION_FRANCE" -> "France",
    "CIVILIZATION_GERMANY" -> "Germany",
    "CIVILIZATION_GREECE" -> "Greece",
    "CIVILIZATION_INDIA" -> "India",
    "CIVILIZATION_IROQUOIS" -> "The Iroquois",
    "CIVILIZATION_JAPAN" -> "Japan",
    "CIVILIZATION_OTTOMAN" -> "The Ottomans",
    "CIVILIZATION_PERSIA" -> "Persia",
    "CIVILIZATION_ROME" -> "Rome",
    "CIVILIZATION_RUSSIA" -> "Russia",
    "CIVILIZATION_SIAM" -> "Siam",
    "CIVILIZATION_SONGHAI" -> "Songhai",
    "CIVILIZATION_MINOR" -> "City State",
    "CIVILIZATION_BARBARIAN" -> "Barbarians",
    "CIVILIZATION_MONGOL" -> "Mongolia",
    "CIVILIZATION_INCA" -> "The Inca",
    "CIVILIZATION_SPAIN" -> "Spain",
    "CIVILIZATION_POLYNESIA" -> "Polynesia",
    "CIVILIZATION_DENMARK" -> "Denmark",
    "CIVILIZATION_KOREA" -> "Korea",
    "CIVILIZATION_BABYLON" -> "Babylon",
    "CIVILIZATION_AUSTRIA" -> "Austria",
    "CIVILIZATION_BYZANTIUM" -> "Byzantium",
    "CIVILIZATION_CARTHAGE" -> "Carthage",
    "CIVILIZATION_CELTS" -> "The Celts",
    "CIVILIZATION_ETHIOPIA" -> "Ethiopia",
    "CIVILIZATION_HUNS" -> "The Huns",
    "CIVILIZATION_MAYA" -> "The Maya",
    "CIVILIZATION_NETHERLANDS" -> "The Netherlands",
    "CIVILIZATION_SWEDEN" -> "Sweden",
    "CIVILIZATION_ASSYRIA" -> "Assyria",
    "CIVILIZATION_BRAZIL" -> "Brazil",
    "CIVILIZATION_INDONESIA" -> "Indonesia",
    "CIVILIZATION_MOROCCO" -> "Morocco",
    "CIVILIZATION_POLAND" -> "Poland",
    "CIVILIZATION_PORTUGAL" -> "Portugal",
    "CIVILIZATION_SHOSHONE" -> "The Shoshone",
    "CIVILIZATION_VENICE" -> "Venice",
    "CIVILIZATION_ZULU" -> "The Zulus"
  )
}
