"""Building metadata: era lookup, building_info flags, and unique-building groups.

Sources (generated by ``db_util/db_export.py``):
  * ``db_util/out/building_info.csv``  — era + wonder/religious flags per building
  * ``db_util/out/unique_buildings.json`` — {base_building: [unique, ...]}
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field

import pandas as pd

from .config import (
    BUILDING_INFO_CSV,
    CIV_COLORS_CSV,
    UNIQUE_BUILDINGS_JSON,
    UNIT_INFO_CSV,
    WONDER_ERAS_CSV,
)

# 1-indexed era numbers (matches the design; DB era is 0-indexed, so DB era n
# corresponds to ERA_LUT[n + 1]).
ERA_LUT: dict[int, str] = {
    1: "Ancient",
    2: "Classical",
    3: "Medieval",
    4: "Renaissance",
    5: "Industrial",
    6: "Modern",
    7: "Atomic",
    8: "Information",
    9: "Future",
}

# Eras offered in the "Building Era" filter (Ancient through Information).
BUILDING_FILTER_ERAS: list[str] = [
    "Ancient",
    "Classical",
    "Medieval",
    "Renaissance",
    "Industrial",
    "Modern",
    "Atomic",
    "Information",
]


def db_era_to_name(db_era: int) -> str | None:
    """Map a 0-indexed DB era to its display name (DB 0 -> Ancient)."""
    return ERA_LUT.get(int(db_era) + 1)


# Turn buckets: the alternative (era-independent) slicing offered by the religion
# report, so yields can be read against the game clock instead of the
# variable-length, per-player eras. Turns outside [START, END) are dropped.
TURN_BUCKET_START = 0  # inclusive lower edge of the first bucket
TURN_BUCKET_END = 300  # exclusive upper edge of the last bucket
TURN_BUCKET_WIDTH = 10


def turn_bucket_starts() -> list[int]:
    """Lower edge of each bucket, in order: [0, 10, ..., 290]."""
    return list(range(TURN_BUCKET_START, TURN_BUCKET_END, TURN_BUCKET_WIDTH))


def turn_bucket_label(start: int) -> str:
    """Display label for a bucket keyed by its lower edge (60 -> '60-69')."""
    return f"{int(start)}-{int(start) + TURN_BUCKET_WIDTH - 1}"


@dataclass
class BuildingInfo:
    name: str
    era: str | None
    is_world_wonder: bool
    is_national_wonder: bool
    is_religious: bool
    is_corp_hq: bool = False
    is_corp_office: bool = False
    is_unique: bool = False
    replaces: str | None = None  # base building this unique replaces


@dataclass
class Metadata:
    buildings: dict[str, BuildingInfo]
    # base building -> list of unique replacements (only bases that have uniques)
    unique_groups: dict[str, list[str]]
    # unique building -> base building it replaces
    unique_to_base: dict[str, str] = field(default_factory=dict)

    @property
    def unique_names(self) -> set[str]:
        return set(self.unique_to_base)


def _parse_bool(value: object) -> bool:
    return str(value).strip().lower() == "true"


def load_metadata() -> Metadata:
    df = pd.read_csv(BUILDING_INFO_CSV, dtype=str).fillna("")
    with open(UNIQUE_BUILDINGS_JSON, encoding="utf-8") as fh:
        unique_groups: dict[str, list[str]] = json.load(fh)

    unique_to_base: dict[str, str] = {}
    for base, uniques in unique_groups.items():
        for uniq in uniques:
            unique_to_base[uniq] = base

    buildings: dict[str, BuildingInfo] = {}
    for _, row in df.iterrows():
        name = row["building"].strip()
        if not name:
            continue
        buildings[name] = BuildingInfo(
            name=name,
            era=row["era"].strip() or None,
            is_world_wonder=_parse_bool(row["is_world_wonder"]),
            is_national_wonder=_parse_bool(row["is_national_wonder"]),
            is_religious=_parse_bool(row["is_religious"]),
            is_corp_hq=_parse_bool(row.get("is_corp_hq", "")),
            is_corp_office=_parse_bool(row.get("is_corp_office", "")),
            is_unique=name in unique_to_base,
            replaces=unique_to_base.get(name),
        )

    return Metadata(
        buildings=buildings,
        unique_groups=unique_groups,
        unique_to_base=unique_to_base,
    )


# ===========================================================================
# Wonders report metadata
# ===========================================================================

# Era display order for the wonders report (Ancient through Information); world
# wonders never unlock in the Future era.
WONDER_ERAS: list[str] = list(BUILDING_FILTER_ERAS)

# Era per era-segment color, sampled from the ``inferno`` colormap over
# [0.05, 0.95] — the palette the R prototype used
# (analysis/r_scripts/14b_wonders_stacked_bar.R, variant "b").
ERA_COLORS: dict[str, str] = {
    "Ancient": "#0C051F",
    "Classical": "#380C5B",
    "Medieval": "#6D186D",
    "Renaissance": "#A12B61",
    "Industrial": "#D14743",
    "Modern": "#F0751E",
    "Atomic": "#F9B01C",
    "Information": "#FAEA76",
}

# Unlock era for the six world wonders missing from wonder_eras.csv. That export
# inner-joins Buildings -> Technologies (db_util/db_export.py:export_wonder_eras),
# so wonders with no PrereqTech — the ones VP gates behind ideologies, policy
# finishers or the World Congress — drop out entirely. They are too commonly
# built to discard (Grand Canal and Menin Gate appear in ~80% of games), so their
# era is pinned here, taken from the modal game-state era (civ_turn_era) of the
# civ that built them at the turn they completed.
WONDER_ERA_OVERRIDES: dict[str, str] = {
    "Grand Canal": "Renaissance",
    "Crystal Palace": "Modern",
    "Menin Gate": "Modern",
    "Olympic Village": "Atomic",
    "United Nations": "Atomic",
    "International Space Station": "Information",
}


def load_wonder_eras() -> dict[str, str]:
    """World wonder name -> unlock era, including :data:`WONDER_ERA_OVERRIDES`."""
    df = pd.read_csv(WONDER_ERAS_CSV, dtype=str).fillna("")
    eras = {
        row["Name"].strip(): row["Era"].strip()
        for _, row in df.iterrows()
        if row["Name"].strip() and row["Era"].strip()
    }
    eras.update(WONDER_ERA_OVERRIDES)
    return eras


# ===========================================================================
# Unit-composition report metadata
# ===========================================================================

# Unit unlock eras offered in the "Unit Era" filter (Ancient through Information),
# mirroring the building-era filter.
UNIT_FILTER_ERAS: list[str] = list(BUILDING_FILTER_ERAS)

# Colored bar categories, in the fixed legend display order. Each entry is
# (key, label, color); ``unit_category`` resolves a unit to one of these keys.
UNIT_CATEGORIES: list[tuple[str, str, str]] = [
    ("melee_infantry", "Melee Infantry", "#2e7d32"),   # dark green
    ("ranged_infantry", "Ranged Infantry", "#8bc34a"),  # light green
    ("melee_cavalry", "Melee Cavalry", "#6d4c2f"),      # dark brown
    ("ranged_cavalry", "Ranged Cavalry", "#c9a26b"),    # light brown
    ("melee_naval", "Melee Naval", "#1565c0"),          # dark blue
    ("ranged_naval", "Ranged Naval", "#64b5f6"),        # light blue
    ("air", "Air", "#ffffff"),                          # white
    ("non_combat", "Non-Combat", "#6a1b9a"),            # dark purple
]

_UNIT_CATEGORY_COLOR: dict[str, str] = {key: color for key, _, color in UNIT_CATEGORIES}


def unit_category(
    *, domain: str, is_ranged: bool, is_mounted: bool, is_combat: bool
) -> str:
    """Resolve a unit to a legend category key (non-combat takes precedence)."""
    if not is_combat:
        return "non_combat"
    if domain == "Air":
        return "air"
    if domain == "Sea":
        return "ranged_naval" if is_ranged else "melee_naval"
    # Land (and any other domain) -> infantry/cavalry split.
    if is_mounted:
        return "ranged_cavalry" if is_ranged else "melee_cavalry"
    return "ranged_infantry" if is_ranged else "melee_infantry"


def _to_bool01(value: object) -> bool:
    return str(value).strip() in {"1", "1.0", "True", "true"}


def load_unit_metadata() -> dict[str, dict]:
    """unit name -> {era, combat_class, domain, is_unique, is_ranged, is_mounted,
    is_combat, non_combat, category, color}."""
    df = pd.read_csv(UNIT_INFO_CSV, dtype=str).fillna("")
    out: dict[str, dict] = {}
    for _, row in df.iterrows():
        name = row["unit"].strip()
        if not name:
            continue
        domain = row["domain"].strip()
        is_ranged = _to_bool01(row["is_ranged"])
        is_mounted = _to_bool01(row["is_mounted"])
        is_combat = _to_bool01(row["is_combat"])
        category = unit_category(
            domain=domain,
            is_ranged=is_ranged,
            is_mounted=is_mounted,
            is_combat=is_combat,
        )
        out[name] = {
            "era": row["era"].strip() or None,
            "combat_class": row["combat_class"].strip(),
            "domain": domain,
            "is_unique": _to_bool01(row["is_unique"]),
            "is_ranged": is_ranged,
            "is_mounted": is_mounted,
            "is_combat": is_combat,
            "non_combat": not is_combat,
            "category": category,
            "color": _UNIT_CATEGORY_COLOR[category],
        }
    return out


# Non-playable "civs" in civ_colors.csv that are not major civilizations.
_NON_MAJOR_CIVS = {"City State", "Barbarians"}


def load_civ_list() -> list[str]:
    """The 43 major civilizations (civ_colors.csv minus City State/Barbarians)."""
    df = pd.read_csv(CIV_COLORS_CSV, dtype=str).fillna("")
    civs = [c.strip() for c in df["civ"] if c.strip() and c.strip() not in _NON_MAJOR_CIVS]
    # Preserve file order but drop any accidental duplicates.
    seen: set[str] = set()
    ordered: list[str] = []
    for c in civs:
        if c not in seen:
            seen.add(c)
            ordered.append(c)
    return ordered
