"""Building metadata: era lookup, building_info flags, and unique-building groups.

Sources (generated by ``db_util/db_export.py``):
  * ``db_util/out/building_info.csv``  — era + wonder/religious flags per building
  * ``db_util/out/unique_buildings.json`` — {base_building: [unique, ...]}
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field

import pandas as pd

from .config import BUILDING_INFO_CSV, UNIQUE_BUILDINGS_JSON

# 1-indexed era numbers (matches the design; DB era is 0-indexed, so DB era n
# corresponds to ERA_LUT[n + 1]).
ERA_LUT: dict[int, str] = {
    1: "Ancient",
    2: "Classical",
    3: "Medieval",
    4: "Renaissance",
    5: "Industrial",
    6: "Modern",
    7: "Atomic",
    8: "Information",
    9: "Future",
}

# Eras offered in the "Building Era" filter (Ancient through Information).
BUILDING_FILTER_ERAS: list[str] = [
    "Ancient",
    "Classical",
    "Medieval",
    "Renaissance",
    "Industrial",
    "Modern",
    "Atomic",
    "Information",
]


def db_era_to_name(db_era: int) -> str | None:
    """Map a 0-indexed DB era to its display name (DB 0 -> Ancient)."""
    return ERA_LUT.get(int(db_era) + 1)


@dataclass
class BuildingInfo:
    name: str
    era: str | None
    is_world_wonder: bool
    is_national_wonder: bool
    is_religious: bool
    is_unique: bool = False
    replaces: str | None = None  # base building this unique replaces


@dataclass
class Metadata:
    buildings: dict[str, BuildingInfo]
    # base building -> list of unique replacements (only bases that have uniques)
    unique_groups: dict[str, list[str]]
    # unique building -> base building it replaces
    unique_to_base: dict[str, str] = field(default_factory=dict)

    @property
    def unique_names(self) -> set[str]:
        return set(self.unique_to_base)


def _parse_bool(value: object) -> bool:
    return str(value).strip().lower() == "true"


def load_metadata() -> Metadata:
    df = pd.read_csv(BUILDING_INFO_CSV, dtype=str).fillna("")
    with open(UNIQUE_BUILDINGS_JSON, encoding="utf-8") as fh:
        unique_groups: dict[str, list[str]] = json.load(fh)

    unique_to_base: dict[str, str] = {}
    for base, uniques in unique_groups.items():
        for uniq in uniques:
            unique_to_base[uniq] = base

    buildings: dict[str, BuildingInfo] = {}
    for _, row in df.iterrows():
        name = row["building"].strip()
        if not name:
            continue
        buildings[name] = BuildingInfo(
            name=name,
            era=row["era"].strip() or None,
            is_world_wonder=_parse_bool(row["is_world_wonder"]),
            is_national_wonder=_parse_bool(row["is_national_wonder"]),
            is_religious=_parse_bool(row["is_religious"]),
            is_unique=name in unique_to_base,
            replaces=unique_to_base.get(name),
        )

    return Metadata(
        buildings=buildings,
        unique_groups=unique_groups,
        unique_to_base=unique_to_base,
    )
